Provide a documentation for TypeScript FA2 API.
oxheadalpha/nft-tutorial pull request #42
Opened 2022-01-20 19:28 UTC by alex-kooper

2022-01-20 19:48 UTC, emishur requested changes
- Also needs a section documenting `Fa2Contract` interface in details just as the rest of the package API
- `Fa2Contract.updateOperators()` parameters doc does not reflect recent changes

2022-01-20 19:48 UTC, emishur commented on packages/fa2-interfaces/README.md
> +### Taquito Wrappers Providing Type-Safe Contract API
Update TOC to refer newly added headers

2022-01-20 19:48 UTC, emishur commented on packages/fa2-interfaces/README.md
> +a "lambda view" to be used in FA2 API.
replace "lambda view" with a link to a Taquito documentation explaining what lambda views are and how to use them

2022-01-20 19:48 UTC, emishur commented on packages/fa2-interfaces/README.md
> +anyway possible, including using `TypeScript` `class`. In this case it has
I do not think that "Typescript" and "class" should be highlighted here

2022-01-20 19:48 UTC, emishur commented on packages/fa2-interfaces/README.md
> +const tezos = new TezosToolkit('https://YOUR_PREFERRED_RPC_URL');
Maybe `TEZOS_NODE_RPC_URL` instead of `YOUR_PREFERRED_RPC_URL`

2022-01-20 20:08 UTC, emishur commented on packages/fa2-interfaces/README.md
> +In FA2 API methods that update contract storage return `Taquito` type
`update contract storage` is not correct description.
Consider using "FA2 API methods that call/invoke contract entry points" instead

2022-01-20 20:15 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +const tezos = new TezosToolkit('https://YOUR_PREFERRED_RPC_URL');
I copy & pasted it from Taquito documentation. That's what they use.

2022-01-20 20:18 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +In FA2 API methods that update contract storage return `Taquito` type
Fixed this

2022-01-20 20:19 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +anyway possible, including using `TypeScript` `class`. In this case it has
Unhighlighted them.

2022-01-20 20:25 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +a "lambda view" to be used in FA2 API.
Did it, created a link.

2022-01-20 20:30 UTC, emishur commented on packages/fa2-interfaces/README.md
> +### Taquito Wrappers Providing Type-Safe Contract API
Still did not update the TOC

2022-01-20 22:29 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +### Taquito Wrappers Providing Type-Safe Contract API
Just did it.

2022-01-20 22:36 UTC, emishur requested changes

2022-01-20 22:36 UTC, emishur commented on packages/fa2-interfaces/README.md
> +### FA2 Contract API Methods
I would follow the same pattern as the API description in the previous section.
I. e. just cut and paste a snippet of code with the API function signature and typescript doc

2022-01-20 22:39 UTC, emishur commented on packages/fa2-interfaces/README.md
> +    { owner: 'tzOnwer3', operator: 'tzOperator3', token_id: 3 },
Misspelled "Owner" here and other places (search for "Onwer")

2022-01-20 22:46 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +    { owner: 'tzOnwer3', operator: 'tzOperator3', token_id: 3 },
Fixed

2022-01-20 22:52 UTC, alex-kooper commented on packages/fa2-interfaces/README.md
> +### FA2 Contract API Methods
It is too much and becomes unreadable.

2022-01-21 00:29 UTC, emishur approved these changes

2022-01-21 00:29 UTC, merged