fa2-contracts doc
oxheadalpha/nft-tutorial pull request #69
Opened 2022-02-26 22:44 UTC by emishur

2022-02-28 23:51 UTC, alex-kooper requested changes

2022-02-28 23:51 UTC, alex-kooper commented on packages/fa2-contracts/README.md
> +in TypeScript source code location (`./src` in our case).
I think it should be "two arguments: **the** name of the specification file and **the** name of the resulting"

2022-02-28 23:51 UTC, alex-kooper commented on packages/fa2-contracts/README.md
> +a generated file, your package must include dependencies on `@taquito/taquito` and
I think it should be "your package must have include dependencies on"

2022-02-28 23:51 UTC, alex-kooper commented on packages/fa2-contracts/README.md
> +If a contract has mint/burn functionality, you haver to select
Typo, it should be "have" not "haver"

2022-02-28 23:51 UTC, alex-kooper commented on packages/fa2-contracts/README.md
> +* `withNoMinterAdmin()` no minter admin. Anyone can mint/burn tokens
Probably a period "." at the end of the second sentence.

2022-03-01 02:25 UTC, emishur commented on packages/fa2-contracts/README.md
> +  mint and burn tokens. Minter admin list is separate from the contract admin(s)
contract admin(s) may be a list or may be not (single admin)

2022-03-01 02:34 UTC, emishur commented on packages/fa2-contracts/README.md
> +a generated file, your package must include dependencies on `@taquito/taquito` and
I think it should be left as is

2022-03-01 14:47 UTC, alex-kooper approved these changes

2022-03-01 15:50 UTC, merged